#!/usr/bin/env bash
# Regenerate the codex app-server protocol bindings.
# Requires codex-cli ≥0.130.0 on PATH.
set -euo pipefail
OUT="src/control/codex/protocol"
rm -rf "$OUT"
mkdir -p "$OUT"
codex app-server generate-ts --experimental --out "$OUT"
cat > "$OUT/README.md" <<'MD'
# codex app-server protocol bindings (auto-generated)

Generated by `npm run codex:gen-types` (`scripts/gen-codex-types.sh`).
**DO NOT EDIT BY HAND.** Re-run the generator to update.

Source: `codex app-server generate-ts --experimental --out <here>` against
`codex-cli ≥0.130.0`. See `docs/specs/2026-05-20-cockpit-interactive-codex-design.md` §3.3.
MD
echo "Generated $OUT"
